### ISSUE TITLE
Shift Select

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#127]
Holding Shift while using a selection tool allows geographies to be added to a selection. 

Geographies cannot be subtracted from the selection if a selected geography is clicked on. This is the expected behavior with this sort of feature.

**Comment by dzwarg** [comment]
Hello,

With an existing selection, shift-clicking on a new geography will add it to the selection. Shift-clicking on an existing geography does nothing.  _Control_-clicking on a new geography does nothing, but _control_-clicking on an existing geography removes it from the selection.

These keyboard shortcuts are common to most graphics editing tools, which is why shift is "add" and control is "remove".
