### ISSUE TITLE
Add link to original data

### ISSUE THREAD

**Issue by andrewjennings** [PublicMapping/districtbuilder-classic#242]

**Comment by maltman** [comment]
This should also be available from the plan chooser.

If the link to original data is only on the "share" tab, someone has to choose a specific plan to get the original data for any plans. There is no underlying business logic for this requirement -- so it  seems unnatural to require it in the UI.

**Comment by andrewjennings** [comment]
I agree that the "share" tab isn't a great choice for this data.  Abby and I spoke about an appropriate place for it and concluded that the link works best on the front page.  It's separate from the workflow of creating districts, choosing plans and working with DB in general.  So we put a link on the front page to resources on the Public Mapping page and to the data hosted there.

**Comment by maltman** [comment]
Somewhere in moving this discussion from ticket to ticket we've lost sight
of the requirement, which is not at all addressed by the solution proposed
below.

The requirement is to expose for public download the core data {shapefile
layers  + subjects} required to reproduce that current working instance.

thanks,

Micah

On Wed, Feb 29, 2012 at 2:31 PM, Andrew Jennings <
reply@reply.github.com

> wrote:
> 
> I agree that the "share" tab isn't a great choice for this data.  Abby and
> I spoke about an appropriate place for it and concluded that the link works
> best on the front page.  It's separate from the workflow of creating
> districts, choosing plans and working with DB in general.  So we put a link
> on the front page to resources on the Public Mapping page and to the data
> hosted there.

**Comment by andrewjennings** [comment]
Sorry, Micah.  I put the wrong link in the first time and didn't link my second commit to this issue.  The data is actually on EC2 and that's where the link on the front page should point.

Here's the right link/commit: 68f8f13507eaab75440b2bf9d32c5ec3a073e645.

**Comment by maltman** [comment]
No. Pointing to EC2 does not help.

Recall this was a variant of "shapefile" export, but applied to the entire
database rather than a single plan. Rather than repeating the requirement,
let me give an example of the key use case:

( 1 ) Administrator: downloads & installs districtbuilder
( 2 ) Administrator: loads shapefiles and subject data into districtbuilder
using setup.py
( 3 ) Administrator: at any later time administrator modifies data: (we
assumed with version 2.0, this would be using  David's subject management
tools)
( 4 ) Non privileged user (including guest): at any time, a user goes to a
designated page (e.g. Share), is presented with a  URL and/or "button",
getting this url/clicking the button results in delivery of  a zip file
containing shapefiles comprising the  layers and subjects currently used by
the system.

Clearly, pointing at an external static page is not going to satisfy this
requirement. The content must be generated within DistrictBuilder or it
will

On Thu, Mar 1, 2012 at 10:49 AM, Andrew Jennings <
reply@reply.github.com

> wrote:
> 
> Sorry, Micah.  I put the wrong link in the first time and didn't link my
> second commit to this issue.  The data is actually on EC2 and that's where
> the link on the front page should point.
> 
> Here's the right link/commit: 68f8f13507eaab75440b2bf9d32c5ec3a073e645.

**Comment by andrewjennings** [comment]
We agreed that a new export was outside the scope of the issue and decided to make the data directory of DistrictBuilder instances public so that users could grab the same data in the same format used to load the application.  That was done in c9f1972c4678bed78276e617ee124d0c80bbb6ee
